name: Build Datafrog Devcontainer Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile' # Trigger only if Dockerfile changes

  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tag with commit SHA for specific versions
          tags: |
            ghcr.io/${{ github.repository }}/datafrog-dev:latest
            ghcr.io/${{ github.repository }}/datafrog-dev:${{ github.sha }}